version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/electron-main"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/electron-renderer"
    schedule:
      interval: "monthly"
